name: Release

on:
  push:
    branches: ["publish-to-s3"]

jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
      # - name: "Debug"
      #   env:
      #     aws_region: eu-west-1
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      #     role_duration_seconds: 3600
      #   run: |
      #     echo "debug" > /tmp/debug.txt
      #     echo "$aws_region" >> /tmp/debug.txt
      #     echo "$aws_access_key_id" >> /tmp/debug.txt
      #     echo "$aws_secret_access_key" >> /tmp/debug.txt
      #     echo "$role_to_assume" >> /tmp/debug.txt
      #     echo "$role_duration_seconds" >> /tmp/debug.txt
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
      - uses: actions/checkout@master
        with:
          # Will fetch all history and tags required to generate version
          fetch-depth: 0
      - uses: actions/setup-go@v1
        with:
          go-version: "1.15.2"
      - name: "Checkup"
        run: go env GOPATH
      - name: "Install dependencies"
        run: |
          go get -v ./...
          go get github.com/inconshreveable/mousetrap
      - name: "Build"
        run: go build
      - name: Git Version
        id: generate-version
        uses: codacy/git-version@2.4.0
      - name: "Tag version"
        run: |
          git tag ${{ steps.generate-version.outputs.version }}
          git push --tags "https://codacy:${{ secrets.GITHUB_TOKEN }}@github.com/codacy/pulse-event-cli"
      - name: "Docker login"
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: "Push binaries to artifacts.codacy.com"
        run: |
          BUCKET=$(aws ssm get-parameter --name "/codacy/artifacts/public/bucket" --query Parameter.Value --output text)
          CLOUDFRONT_ID=$(aws ssm get-parameter --name "/codacy/artifacts/public/cloudfront_id" --query Parameter.Value --output text)
          BINARY_PATH="codacy/pulse/event-cli"
          for binary_directory in $(find dist -type d -iname 'pulse-event-cli_*' | awk -F'/' '{print $2}')
          do
            binary="$(ls dist/$binary_directory)"
            echo "Pushing dist/$binary_directory/$binary to bintray"
            aws s3 cp "dist/$binary_directory/$binary" s3://${BUCKET}/${BINARY_PATH}/${{ steps.generate-version.outputs.version }}/$binary_directory/$binary
          done

          # If it is a stable version then publish to latest file with current version and invalidate cloudfront cache
          if $(echo "${{ steps.generate-version.outputs.version }}" | grep -q -E '^[0-9]+\.[0-9]+\.[0-9]+$'); then
            echo "${{ steps.generate-version.outputs.version }}" | tr -d '\n' | aws s3 cp - s3://${BUCKET}/${BINARY_PATH}/latest
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/${BINARY_PATH}/latest"
          fi
      - name: "Push data to pulse"
        uses: codacy/pulse-action@0.0.3
        with:
          args: |
            push git deployment \
              --api-key ${{ secrets.PULSE_ORGANIZATION_PULSE_API_KEY }} \
              --system $GITHUB_REPOSITORY \
              --previous-deployment-ref ${{ steps.generate-version.outputs.previous-version }} \
              --identifier ${{ steps.generate-version.outputs.version }} \
              --timestamp "$(date +%s)"
